# Generated by Django 5.2 on 2026-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='contact',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='project_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
